### ISSUE TITLE
UnicodeDecodeError when add a file containing Chinese character

### ISSUE THREAD

**Issue by bethmal** [gitlabform/gitlabform#260] opened 2021-08-24 08:16 UTC
Hi,

With gitlabform v2.2.0, hit below exception when add a file that contains Chinese character.

UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 129: illegal multibyte sequence

**Comment by gdubicki** [comment] 2021-09-05 07:00
Hi @bethmal !

Sorry for the late response.

I have added 2 tests for managing file contents to include Chinese characters in https://github.com/egnyte/gitlabform/pull/269/files .

Is that what has failed for you?

An exempt from the config file and/or the file that is failing for you would be very helpful. Perhaps also the platform matters here - on what OS are you running GitLabForm?

**Comment by bethmal** [comment] 2021-09-07 07:41
Hi @gdubicki ,

The file to be uploaded is attached.

I have the configuration as below to add license file into git repo.

    branches:
      # see comment above - this branch config will be ADDED to the branches configured on a group level
      master:
        protected: true
        push_access_level: 40
        merge_access_level: 40
        unprotect_access_level: 40

    files:
      "LICENSE":
        overwrite: true
        branches: all
        skip_ci: true
        file: LICENSE.md

[LICENSE.md](https://github.com/egnyte/gitlabform/files/7119812/LICENSE.md)

**Comment by gdubicki** [comment] 2022-11-30 10:56
I am going to close this as I was not able to reproduce it. Please reopen if you still have the problem, @bethmal or anyone else.

**Closed by gdubicki** 2022-11-30 10:56 UTC
Labels: 🐛bug
