### ISSUE TITLE
Project API: public_jobs versus public_builds

### ISSUE THREAD

**Issue by felsgaertner** [gitlabform/gitlabform#542] opened 2023-05-05 14:55 UTC
**Describe the bug**

I want to control the flag "Settings > CI/CD > General pipelines > Public pipelines", but I have the following problem:

Running 
~~~yaml
projects_and_groups:

  "*":
    project_settings:
      public_builds: true
      public_jobs: true
~~~
with -v -n ALL returns:

~~~ text
Processing section 'project_settings' in dry-run mode.
project_settings changes:
 public_builds: "???"  => true
   public_jobs: false  => true
~~~

The problem is directly related to GitLabs API: the input parameter is called "public_builds", but returned as output parameter "public_jobs". The comparison on public_jobs works fine, but does not change anything when run without "-n". You have to specify *public_builds* to change that flag, but there is no comparison between current and new state.

So until Gitlab changes this naming mismatch, you should send *public_builds* to the API where *public_jobs* should be changed. In other words, map public_builds and public_jobs to the same meaning, depending on the http request (GET, PUT, POST).

**GitLabForm version**

Container :latest = 3.5.0 

**GitLab version**

GitLab version: 15.10.1 (a2b7634113a)

----

GitLab bug report: https://gitlab.com/gitlab-org/gitlab/-/issues/409851

**Comment by nejch** [comment] 2023-05-10 10:09
This is a known discrepancy in the API, your upstream issue is probably a duplicate of https://gitlab.com/gitlab-org/gitlab/-/issues/329725.

We also had this reported in https://github.com/python-gitlab/python-gitlab/issues/1428.

**Comment by amimas** [comment] 2024-03-30 13:47
@felsgaertner - thanks for bringing this up. Since it's a gitlab issue, going to close it. Feel free to reopen it if I misunderstood.

**Closed by amimas** 2024-03-30 13:47 UTC
Labels: 🦊gitlab issue
