### ISSUE TITLE
Unable deactivate service: jira

### ISSUE THREAD

**Issue by glensc** [gitlabform/gitlabform#102] opened 2020-05-21 18:09 UTC
I'd like to deactivate a service (not delete):

```yaml
project_settings:
  "glen/playground":
    services:
      jira:
        active: false
```

but this gives api error:

```
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://gitlab.example.net/api/v4/projects/glen%2Fplayground/services/jira', method=PUT, data='None' failed - expected code(s) [200, 201], got code 400 & body: 'b'{"error":"url is missing, username is missing, password is missing"}''
```

however, it's perfectly possible to do that from gitlab own UI. just click on the active checkbox and save.

**Comment by gdubicki** [comment] 2020-05-28 17:28
Unfortunately it seems that it's one of the many inconsistencies in the GitLab APIs - although the docs say that you can make the integration active or not (https://docs.gitlab.com/ee/api/services.html#get-jira-service-settings), both my tests and this issue suggest that this feature does not work via the API: https://gitlab.com/gitlab-org/gitlab/-/issues/22289

**Comment by gdubicki** [comment] 2020-05-28 17:31
I tried working around the issue by deleting the active service and creating it anew as inactive but it did not work - service is always created as active.

**Comment by gdubicki** [comment] 2020-07-07 12:20
Maybe that's obvious but as a workaround I would just delete the service (`delete: true`) instead of disabling. Without GitLabForm, using the web UI it makes some sense to disable instead of deleting because if you delete then you have to reenter all the necessary parameters for the integration to enable it again. But with GitLabForm, where you probably keep the config under the control of a versioning system, there is no such problem.

Hm... Maybe until the issue is fixed on GitLab side we should just implement such a behaviour in GitLabForm? I mean: we could react to `active: false` with just deleting the service.

What do you think about that @glensc ?

**Comment by glensc** [comment] 2020-07-08 07:27
@gdubicki yers, that's what you call workaround, and it's noted in initial issue description too that I do not wish to delete:

> I'd like to deactivate a service (not delete)

so implementing as delete instead of deactivating loses data, and should not be done that way. must let user decide to do delete or manage the service some other way.

**Comment by amimas** [comment] 2024-03-17 18:19
@glensc - would you be able to confirm if this issue still exists? Even if it does, I think we should probably close this one because unless it's fixed on GitLab's side, sounds like nothing we can do in GitLabForm. What do you think?

**Comment by glensc** [comment] 2024-03-17 20:31
@amimas: Sorry, I no longer use JIRA.

**Comment by glensc** [comment] 2024-03-17 20:34
I can still test whether the reported issue still exists, but the feature is no longer valuable to me.

I ended up running one time `delete: true` and be done with the integratio.

**Comment by amimas** [comment] 2024-03-28 20:03
Thanks @glensc . It'd be great if you're able to test if it exists and update this thread. For now, I'm going to close this based on `gitlab issue` label because in that case, there's probably nothing we can do. If I'm mistaken or if there's something gitlabform can do, feel free to reopen it.

**Closed by amimas** 2024-03-28 20:03 UTC
Labels: 🦊gitlab issue

**Comment by glensc** [comment] 2024-03-30 12:05
it seems to be the same (gives some error).

```
✖ pip list |grep gitlabform
gitlabform         3.9.2

➜ gitlabform --skip-version-check -c config.yml glen/playground 
🏗  GitLabForm version: 3.1.2 
>>> Getting requested groups/projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: glen/playground
Warning: Error occurred while processing project glen/playground, exception:

Request url='https://gitlab.local/api/v4/projects/glen%2Fplayground', method=PUT, json='{"glen/playground": {"services": {"jira": {"active": false}}}}' failed - expected code(s) [200], got code 400 & body: '{"error":"allow_merge_on_skipped_pipeline, analytics_access_level, autoclose_referenced_issues, auto_devops_enabled, auto_devops_deploy_strategy, auto_cancel_pending_pipelines, build_git_strategy, build_timeout, builds_access_level, ci_config_path, ci_default_git_depth, ci_allow_fork_pipelines_to_run_in_parent_project, ci_forward_deployment_enabled, ci_forward_deployment_rollback_allowed, ci_separated_caches, container_registry_access_level, container_expiration_policy_attributes, default_branch, description, emails_disabled, emails_enabled, forking_access_level, issues_access_level, lfs_enabled, merge_pipelines_enabled, merge_requests_access_level, merge_requests_template, merge_trains_enabled, merge_method, name, only_allow_merge_if_all_discussions_are_resolved, only_allow_merge_if_pipeline_succeeds, pages_access_level, path, printing_merge_request_link_enabled, public_builds, remove_source_branch_after_merge, repository_access_level, request_access_enabled, resolve_outdated_diff_discussions, restrict_user_defined_variables, show_diff_preview_in_email, security_and_compliance_access_level, squash_option, shared_runners_enabled, group_runners_enabled, snippets_access_level, tag_list, topics, visibility, wiki_access_level, avatar, suggestion_commit_message, merge_commit_template, squash_commit_template, issue_branch_template, repository_storage, packages_enabled, service_desk_enabled, keep_latest_artifact, mr_default_target_self, enforce_auth_checks_on_uploads, releases_access_level, environments_access_level, feature_flags_access_level, infrastructure_access_level, monitor_access_level, model_experiments_access_level, model_registry_access_level, issues_enabled, jobs_enabled, merge_requests_enabled, wiki_enabled, snippets_enabled, container_registry_enabled, allow_pipeline_trigger_approve_deployment, only_allow_merge_if_all_status_checks_passed, approvals_before_merge, external_authorization_classification_label, fallback_approvals_required, import_url, issues_template, mirror, merge_requests_template, merge_pipelines_enabled, merge_trains_enabled, merge_trains_skip_train_allowed, requirements_access_level, prevent_merge_without_jira_issue, ci_restrict_pipeline_cancellation_role are missing, at least one parameter must be provided"}'
:: # of groups processed successfully: 0
:: # of projects processed successfully: 0
:: # of projects failed: 1 
:: Failed project 1: glen/playground 
```

**Comment by amimas** [comment] 2024-03-30 18:55
Thanks for testing it. The error seems different this time.
